#!/usr/bin/env bash

#echo -e ${PATH//:/\\n}

echo '--------'
echo PATH
echo '--------'
echo $PATH | tr ':' '\n'
echo '-----------------'
echo LD_LIBRARY_PATH
echo '-----------------'
echo $LD_LIBRARY_PATH | tr ':' '\n'
