#!/usr/bin/env python3

print("p4 -ztag opened | grep clientFile | awk '{print $3}' | sed 's|^//[^/]*/||'")
print("")
print("vim `p4 -ztag opened | grep clientFile | awk '{print $3}' | sed 's|^//[^/]*/||' | xargs`")

print ("""

# Remove all p4 files to reset the repo status
p4 sync ...#0 > /dev/null

# Find code review author's workspace
p4 changes -m 5 -s pending -u ming
p4 clients|grep client_name

# To create a changelist from the current default changelist
p4 change
# To create a shelved changelist
p4 shelve -c 123456
  # To delete
  p4 shelve -d -c 123456

# To unshelve the files that were shelved from a changelist 123456 back to the default changelist:
p4 unshelve -s 123456
# To unshelve the files that were shelved from a changelist 123456 back to a different changelist 789012:
p4 unshelve -s 123456 -c 789012

p4v | Modify a submitted commit message for a submitted changelist
    Click View
    Click Submitted Changelists

    Or
    Clieck Search
    Click Go To...
      Type the Changelist number
        """)
