#!/usr/bin/env bash

# make sure there is no leftover dmtcp process.

exec ps aux|grep $(whoami)|grep -i dmtcp|grep -v grep

# DMTCP PATH size limitation
# export PATH=/usr/local/bin:/usr/bin:.
  # make sure PATH does not exceed 2KB
  # dmtcp_restart_script.sh
